# Generated by Django 4.1.4 on 2022-12-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0003_rename_alphabet_game_game_id_game_game_word_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_word',
            field=models.CharField(max_length=20),
        ),
    ]
