# Generated by Django 4.1.4 on 2022-12-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0004_alter_game_game_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fill_Letters',
            field=models.CharField(default='', max_length=20),
        ),
    ]
