# Generated by Django 4.1.4 on 2022-12-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0005_game_fill_letters'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='chances',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
